os: Windows Server 2012

environment:
  VisualStudioVersion: 12.0
  NuGetApiKey:
    secure: mM8obSbEhxoOZ31ZPbECaKlqHlmnU/JxDdSTMYRb6UbDtdV+Sw+gBbZIjNlbwZ4V

configuration: Release

before_build:
  - nuget restore src\psbuild.sln

build_script:
  - ps: .\appveyor.ps1

artifacts:
  - path: OutputRoot\**\*.ps*1
  - path: OutputRoot\PSBuild\**\*.dll
  - path: OutputRoot\PSBuild\**\*.pdb
  - path: OutputRoot\**\*.nupkg
